import os

class FrontendGeneratorAgent:
    def generate_files(self, project_id: str, prompt: str, modules: list) -> dict:
        """Generates real Next.js + Tailwind TSX page stubs on disk."""
        base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../generated_projects", project_id, "frontend"))
        os.makedirs(os.path.join(base_dir, "pages"), exist_ok=True)
        os.makedirs(os.path.join(base_dir, "components"), exist_ok=True)

        module = modules[0].lower() if modules else "dashboard"
        module_title = module.capitalize()

        # pages/index.tsx
        page_code = f"""import React from "react";

export default function {module_title}Page() {{
  return (
    <div className="min-h-screen bg-slate-950 text-white p-8 font-sans">
      <h1 className="text-2xl font-bold text-indigo-400 mb-4">{module_title} Management</h1>
      <p className="text-slate-400 mb-6">Generated by ContextForge AI Frontend Generator Agent.</p>
      
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-4 shadow-lg">
        <h2 className="text-sm font-semibold text-slate-200 mb-2">Active {module_title} Records</h2>
        <div className="text-xs text-slate-400">Loading data from FastAPI backend...</div>
      </div>
    </div>
  );
}}
"""
        with open(os.path.join(base_dir, f"pages/{module}.tsx"), "w", encoding="utf-8") as f:
            f.write(page_code)

        # components/DataTable.tsx
        table_code = f"""import React from "react";

export function {module_title}Table({{ items }}: {{ items: any[] }}) {{
  return (
    <table className="w-full text-left text-xs text-slate-300">
      <thead className="bg-slate-800 text-slate-400 font-mono">
        <tr>
          <th className="p-2">ID</th>
          <th className="p-2">Name</th>
          <th className="p-2">Status</th>
        </tr>
      </thead>
      <tbody>
        {{items.map((item, idx) => (
          <tr key={{idx}} className="border-b border-slate-800">
            <td className="p-2">{{item.id}}</td>
            <td className="p-2 font-medium text-white">{{item.name}}</td>
            <td className="p-2 text-emerald-400">{{item.status}}</td>
          </tr>
        ))}}
      </tbody>
    </table>
  );
}}
"""
        with open(os.path.join(base_dir, f"components/{module_title}Table.tsx"), "w", encoding="utf-8") as f:
            f.write(table_code)

        return {
            "status": "SUCCESS",
            "base_dir": base_dir,
            "generated_files": [
                f"pages/{module}.tsx",
                f"components/{module_title}Table.tsx"
            ]
        }
