class GeneratorAgent:
    def generate_code(self, task_plan: dict, context: dict) -> str:
        return '''from fastapi import APIRouter

router = APIRouter()

@router.get("/context-aware-endpoint")
def sample_endpoint():
    return {"message": "Generated by ContextForge AI with DataHub context"}'''
